// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Transactor is an autogenerated mock type for the Transactor type
type Transactor struct {
	mock.Mock
}

type Transactor_Expecter struct {
	mock *mock.Mock
}

func (_m *Transactor) EXPECT() *Transactor_Expecter {
	return &Transactor_Expecter{mock: &_m.Mock}
}

// WithTransaction provides a mock function with given fields: ctx, f
func (_m *Transactor) WithTransaction(ctx context.Context, f func(context.Context) error) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transactor_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type Transactor_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - f func(context.Context) error
func (_e *Transactor_Expecter) WithTransaction(ctx interface{}, f interface{}) *Transactor_WithTransaction_Call {
	return &Transactor_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, f)}
}

func (_c *Transactor_WithTransaction_Call) Run(run func(ctx context.Context, f func(context.Context) error)) *Transactor_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *Transactor_WithTransaction_Call) Return(_a0 error) *Transactor_WithTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transactor_WithTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *Transactor_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactor creates a new instance of Transactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transactor {
	mock := &Transactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
